### ISSUE TITLE
[BUG] Unable to Save Combat Tracker settings

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-combat-details#49] opened 2023-08-23 21:11 UTC
Encounter Tracker Settings won't save while Combat Details is active.

https://github.com/ironmonk88/monks-combat-details/assets/99844555/3546f3f6-e8cd-44d6-9c1d-73ced22b6882

CD 11.04-11.06
Foundry 11.307
PF2 5.3.2

**Comment by mhilbrunner** [comment] 2023-08-26 06:18
This is caused by the patched save function for encounter settings not checking if `game.combat` is null before trying to access `game.combat.setFlag()`.

**Comment by ironmonk88** [comment] 2023-09-23 03:15
Fixed in the latest release.

**Closed by ironmonk88** 2023-09-23 03:15 UTC
Labels: fixed waiting for release
